### ISSUE TITLE
Why is proposals required to run STMN

### ISSUE THREAD

**Issue by RalphMao** [fanyix/STMN#7]
As far as I know from the paper, STMN adopts R-FCN as the backbone

**Comment by fanyix** [comment]
We are using R-FCN without the RPN. Instead we require proposals computed from DeepMask, as we said in our paper.

**Comment by RalphMao** [comment]
Thank you for your timely reply! Also, may I know the reason why RPN is removed? Is it due to the difficulty of joint training of RPN and classifier?

**Comment by RalphMao** [comment]
@fanyix 
Thank you for your timely reply! 
Also, may I know the reason why RPN is removed? Is it due to the difficulty of joint training of RPN and classifier?

**Comment by fanyix** [comment]
Hi @RalphMao, the main reason for this is that we started with a Fast-RCNN style detector and switched to R-FCN during the development, and at that point we already got pretty good results with pre-computed proposals and therefore did not bother adding a RPN there. 

This being said, there is nothing prevent adding a RPN into our detector and thus avoid using any off-the-shelf proposal methods (in fact I would imagine you will get similar results since we actually tried swapping in the proposals computed from the RPN in D&T [Feichtenhofer et al.] and got very similar results).
